version: "3.8"
services:
  app:
    container_name: cadigo-api-local
    build:
      context: .
      dockerfile: ./build/Dockerfile.local
      args:
        ACCESS_TOKEN:
    volumes:
      - ./:/app/
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8080:8080"
