package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	modelgraph1 "cadigo-api/graph/modelgraph"
	"context"
	"fmt"
)

// Caddy is the resolver for the Caddy field.
func (r *mutationResolver) Caddy(ctx context.Context, input modelgraph1.CaddyInput) (*modelgraph1.Caddy, error) {
	return r.CaddyHandler.Caddy(ctx, input)
}

// GetCaddy is the resolver for the getCaddy field.
func (r *queryResolver) GetCaddy(ctx context.Context, input modelgraph1.GetCaddyInput) (*modelgraph1.Caddy, error) {
	panic(fmt.Errorf("not implemented: GetCaddy - getCaddy"))
}

// GetCaddys is the resolver for the getCaddys field.
func (r *queryResolver) GetCaddys(ctx context.Context, input modelgraph1.GetCaddyInput) (*modelgraph1.CaddyData, error) {
	panic(fmt.Errorf("not implemented: GetCaddys - getCaddys"))
}
