package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"cadigo-api/graph/modelgraph"
	"context"
	"fmt"
)

// CourseGolf is the resolver for the courseGolf field.
func (r *mutationResolver) CourseGolf(ctx context.Context, input modelgraph.CourseGolfInput) (*modelgraph.CourseGolf, error) {
	panic(fmt.Errorf("not implemented: CourseGolf - courseGolf"))
}

// DeleteCourseGolf is the resolver for the deleteCourseGolf field.
func (r *mutationResolver) DeleteCourseGolf(ctx context.Context, id string) (*modelgraph.CourseGolf, error) {
	panic(fmt.Errorf("not implemented: DeleteCourseGolf - deleteCourseGolf"))
}

// GetCourseGolf is the resolver for the getCourseGolf field.
func (r *queryResolver) GetCourseGolf(ctx context.Context, input modelgraph.GetgetCourseGolfInput) (*modelgraph.CourseGolf, error) {
	panic(fmt.Errorf("not implemented: GetCourseGolf - getCourseGolf"))
}

// GetCourseGolfs is the resolver for the getCourseGolfs field.
func (r *queryResolver) GetCourseGolfs(ctx context.Context, input modelgraph.GetgetCourseGolfsInput) (*modelgraph.CourseGolfData, error) {
	panic(fmt.Errorf("not implemented: GetCourseGolfs - getCourseGolfs"))
}
