package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"cadigo-api/graph/modelgraph"
	"context"
)

// CourseGolf is the resolver for the courseGolf field.
func (r *mutationResolver) CourseGolf(ctx context.Context, input modelgraph.CourseGolfInput) (*modelgraph.CourseGolf, error) {
	return r.CoursegolfHandler.CourseGolf(ctx, input)
}

// DeleteCourseGolf is the resolver for the deleteCourseGolf field.
func (r *mutationResolver) DeleteCourseGolf(ctx context.Context, id string) (*modelgraph.CourseGolf, error) {
	return r.CoursegolfHandler.DeleteCourseGolf(ctx, id)
}

// GetCourseGolf is the resolver for the getCourseGolf field.
func (r *queryResolver) GetCourseGolf(ctx context.Context, input modelgraph.GetCourseGolfInput) (*modelgraph.CourseGolf, error) {
	return r.CoursegolfHandler.GetCourseGolf(ctx, input)
}

// GetCourseGolfs is the resolver for the getCourseGolfs field.
func (r *queryResolver) GetCourseGolfs(ctx context.Context, input modelgraph.GetCourseGolfsInput) (*modelgraph.CourseGolfData, error) {
	return r.CoursegolfHandler.GetCourseGolfs(ctx, input)
}
