package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"cadigo-api/graph/modelgraph"
	"context"
	"fmt"
)

// User is the resolver for the user field.
func (r *mutationResolver) User(ctx context.Context, input modelgraph.UserInput) (*modelgraph.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, input modelgraph.GetUserInput) (*modelgraph.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}
