// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package modelgraph

import (
	"fmt"
	"io"
	"strconv"
)

type Booking struct {
	Reference             *string `json:"reference,omitempty" copier:"Reference"`
	CancellationReference *string `json:"cancellationReference,omitempty" copier:"CancellationReference"`
	ClientReference       *string `json:"clientReference,omitempty" copier:"ClientReference"`
	CreationDate          *string `json:"creationDate,omitempty" copier:"CreationDate"`
	Status                *string `json:"status,omitempty" copier:"Status"`
	CreationUser          *string `json:"creationUser,omitempty" copier:"CreationUser"`
	Remark                *string `json:"remark,omitempty" copier:"Remark"`
	TotalSellingRate      *int    `json:"totalSellingRate,omitempty" copier:"TotalSellingRate"`
	TotalNet              *int    `json:"totalNet,omitempty" copier:"TotalNet"`
	PendingAmount         *int    `json:"pendingAmount,omitempty" copier:"PendingAmount"`
}

type BookingData struct {
	Data       []*Booking      `json:"data" copier:"Data"`
	Pagination *PaginationType `json:"pagination" copier:"Pagination"`
}

type BookingInput struct {
	ClientReference *string      `json:"clientReference,omitempty" copier:"ClientReference"`
	Language        LanguageEnum `json:"language" copier:"Language"`
}

type BookingsHistoryInput struct {
	Language   LanguageEnum     `json:"language" copier:"Language"`
	Pagination *PaginationInput `json:"pagination" copier:"Pagination"`
}

type Caddy struct {
	ID           *string   `json:"id,omitempty" copier:"Id"`
	Name         *string   `json:"name,omitempty" copier:"Name"`
	Location     *string   `json:"location,omitempty" copier:"Location"`
	Avialability *string   `json:"avialability,omitempty" copier:"Avialability"`
	Skill        []*string `json:"skill,omitempty" copier:"Skill"`
	Start        *int      `json:"start,omitempty" copier:"Start"`
	Description  *string   `json:"description,omitempty" copier:"Description"`
	Time         []*string `json:"time,omitempty" copier:"Time"`
	Cost         *float64  `json:"cost,omitempty" copier:"Cost"`
}

type CaddyData struct {
	Data       []*Caddy        `json:"data" copier:"Data"`
	Pagination *PaginationType `json:"pagination" copier:"Pagination"`
}

type CaddyInput struct {
	Name         string   `json:"name" copier:"Name"`
	Location     string   `json:"location" copier:"Location"`
	Avialability string   `json:"avialability" copier:"Avialability"`
	Skill        []string `json:"skill,omitempty" copier:"Skill"`
	Start        int      `json:"start" copier:"Start"`
	Description  string   `json:"description" copier:"Description"`
	Time         []string `json:"time,omitempty" copier:"Time"`
	Cost         float64  `json:"cost" copier:"Cost"`
}

type GetBookingInput struct {
	BookingReference *string      `json:"bookingReference,omitempty" copier:"BookingReference"`
	Language         LanguageEnum `json:"language" copier:"Language"`
}

type GetCaddyInput struct {
	Language LanguageEnum `json:"language" copier:"Language"`
	ID       *string      `json:"id,omitempty" copier:"Id"`
}

type GetCaddysInput struct {
	Language   LanguageEnum     `json:"language" copier:"Language"`
	Pagination *PaginationInput `json:"pagination" copier:"Pagination"`
}

type PaginationInput struct {
	Page     int           `json:"page" copier:"Page"`
	Limit    int           `json:"limit" copier:"Limit"`
	OrderBy  *string       `json:"orderBy,omitempty" copier:"OrderBy"`
	Asc      *bool         `json:"asc,omitempty" copier:"Asc"`
	Leyword  []*string     `json:"leyword,omitempty" copier:"Leyword"`
	Language *LanguageEnum `json:"language,omitempty" copier:"Language"`
}

type PaginationType struct {
	Page  int `json:"page" copier:"Page"`
	Limit int `json:"limit" copier:"Limit"`
	Total int `json:"total" copier:"Total"`
}

type LanguageEnum string

const (
	LanguageEnumTh LanguageEnum = "TH"
	LanguageEnumEn LanguageEnum = "EN"
)

var AllLanguageEnum = []LanguageEnum{
	LanguageEnumTh,
	LanguageEnumEn,
}

func (e LanguageEnum) IsValid() bool {
	switch e {
	case LanguageEnumTh, LanguageEnumEn:
		return true
	}
	return false
}

func (e LanguageEnum) String() string {
	return string(e)
}

func (e *LanguageEnum) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LanguageEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LanguageEnum", str)
	}
	return nil
}

func (e LanguageEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
